### PR TITLE
puppet-lint: Allow 4.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hey @jovandeginste, any chance you could merge and release this shortly? Would you be interested in migrating the module to Vox Pupuli so more people can help out with the maintenance?

**Comment by jovandeginste** [comment]
releases with 0.3.0

**Comment by jovandeginste** [comment]
I wouldn't mind migrating to Vox Pupuli, tell me what to do!

**Comment by bastelfreak** [comment]
awesome! I sent you an invitati9n to join the vox pupuli github org. After you accepted it, you can migrate the github repo to us. Then pleaee add pmc@voxpupuli.org as owner on rubygems. Of corse you will keep merge access (if you like). If you have any coworkers or other current maintainers that should keep merge access let me know and I can invite them as well.

**Comment by jovandeginste** [comment]
I believe I performed all steps; I was the only developer for this project, so no need to add other maintainers.

**Comment by bastelfreak** [comment]
awesome! Thanks for all the work you put into the project <3

**Comment by jovandeginste** [comment]
No problem, it was not that much work and well worth it so far. There are some open issues, and I'm still happy to help where I can (but it's probably in better hands now anyway). I hope to learn more, too :-)

**Pull request merged**
